### ISSUE TITLE
Create initial project structure

### ISSUE THREAD

**Issue by wtrocki** [Lavanyagaur22/AerogearTasks#1]
Create Android library and example app. 
Create README explaining what application is doing.

**Comment by Lavanyagaur22** [comment]
@wtrocki Have created a basic structure, can u please tell me exactly what should this library contain? Should it contain the graphql queries to hit the tasks details to the local host server?
I want some clarity regarding what should this library contain?

**Comment by wtrocki** [comment]
Nothing at the moment. Create empty library and example project and call it a day. Later we can talk about library itself, but long story short: Library will be the place where we add conflict resolution and offline, but it is to early to talk about it.

**Comment by wtrocki** [comment]
Lets collaborate using Pull requests and avoid pushing changes to master directly

**Comment by Lavanyagaur22** [comment]
@wtrocki I have made the required changes and added you as a reviewer of the Pr.
